### ISSUE TITLE
Robot doesn't add the environments

### ISSUE THREAD

**Issue by bartdebieUiPath** [wgilder/PrepareBootcampUsers#2]
While environments are shown in the final output excel, they don't seem to be added in the server settings tab.

**Comment by wgilder** [comment]
Can you see if the environments have been added to the Settings page? I suspect the bot just needs to refresh that page in order to activate the environment...

**Comment by bartdebieUiPath** [comment]
The issue i found is that in the settings page it seemed to process something with the environments, but it did not add them to the window there.

**Comment by wgilder** [comment]
could you forward me the users list you used? Perhaps there's something with the names that PM chokes on...

**Comment by wgilder** [comment]
Couldn't reproduce. I have changed the workflow to refresh browser once settings are changed, in order that PM picks up the new environments.
